-- Author: Andrew Jarombek
-- Date: 3/2/2018
-- Create a new table called code_written that contains data for the lines of code written

DROP TABLE code_written CASCADE CONSTRAINTS;

CREATE TABLE code_written(
  written_id INTEGER GENERATED BY DEFAULT AS IDENTITY (
    START WITH 1 INCREMENT BY 1
  ),
  year INTEGER NOT NULL,
  language VARCHAR2(63) NOT NULL,
  lines INTEGER NOT NULL,
  CONSTRAINT code_written_language_fk
    FOREIGN KEY (language) REFERENCES languages(name) ON DELETE CASCADE
);

-- Add a check constraint so the year must be between 2014 and 2018
ALTER TABLE code_written ADD CONSTRAINT code_written_year_ck CHECK (year BETWEEN 2014 AND 2018);

TRUNCATE TABLE code_written CASCADE;

DECLARE
  PROCEDURE code_written_bulk_insert(
    p_year IN code_written.year%TYPE,
    p_language IN code_written.language%TYPE,
    p_lines IN code_written.lines%TYPE
  ) AS
  BEGIN
    INSERT INTO code_written(
      year, language, lines
    ) VALUES (
      p_year, p_language, p_lines
    );
  END;
BEGIN
  code_written_bulk_insert(2018, 'Java', 979);
  code_written_bulk_insert(2018, 'JavaScript', 1120);
  code_written_bulk_insert(2018, 'SQL', 585);
  code_written_bulk_insert(2018, 'C', 0);
  code_written_bulk_insert(2018, 'Python', 242);
  code_written_bulk_insert(2018, 'HTML', 397);
  code_written_bulk_insert(2018, 'XML', 0);
  code_written_bulk_insert(2018, 'PHP', 0);
  code_written_bulk_insert(2018, 'CSS', 34);
  code_written_bulk_insert(2018, 'JSON', 112);
  code_written_bulk_insert(2018, 'PL/SQL', 121);
  code_written_bulk_insert(2018, 'Swift', 103);
  code_written_bulk_insert(2018, 'Sass', 443);
  code_written_bulk_insert(2018, 'TypeScript', 1850);
  code_written_bulk_insert(2017, 'Java', 12113);
  code_written_bulk_insert(2017, 'JavaScript', 6663);
  code_written_bulk_insert(2017, 'SQL', 812);
  code_written_bulk_insert(2017, 'C', 271);
  code_written_bulk_insert(2017, 'Python', 1288);
  code_written_bulk_insert(2017, 'HTML', 1969);
  code_written_bulk_insert(2017, 'XML', 5815);
  code_written_bulk_insert(2017, 'PHP', 3670);
  code_written_bulk_insert(2017, 'CSS', 1654);
  code_written_bulk_insert(2017, 'JSON', 1019);
  code_written_bulk_insert(2017, 'PL/SQL', 844);
  code_written_bulk_insert(2017, 'Swift', 10726);
  code_written_bulk_insert(2017, 'Sass', 163);
  code_written_bulk_insert(2017, 'TypeScript', 133);
  code_written_bulk_insert(2016, 'Java', 12962);
  code_written_bulk_insert(2016, 'JavaScript', 2008);
  code_written_bulk_insert(2016, 'SQL', 942);
  code_written_bulk_insert(2016, 'C', 379);
  code_written_bulk_insert(2016, 'Python', 1122);
  code_written_bulk_insert(2016, 'HTML', 1413);
  code_written_bulk_insert(2016, 'XML', 2646);
  code_written_bulk_insert(2016, 'PHP', 5433);
  code_written_bulk_insert(2016, 'CSS', 1233);
  code_written_bulk_insert(2016, 'JSON', 820);
  code_written_bulk_insert(2016, 'PL/SQL', 203);
  code_written_bulk_insert(2015, 'C', 630);
  code_written_bulk_insert(2015, 'Python', 931);
  code_written_bulk_insert(2015, 'XML', 42);
  code_written_bulk_insert(2015, 'JSON', 32);
  code_written_bulk_insert(2015, 'Java', 1585);
  code_written_bulk_insert(2014, 'Java', 4282);
END;

SELECT * FROM code_written;