-- Author: Andrew Jarombek
-- Date: 2/12/2018
-- Create Tables for the Oracle 12c database

-- List all the users tables.  At this point the list should be empty
SELECT * FROM SYS.USER_TABLES;

-- Cascade constraints drops all the constraints on this table.  If there were constraints and you omitted this line,
-- an error would be thrown when attempting to drop the table
DROP TABLE book_languages CASCADE CONSTRAINTS;
DROP TABLE books CASCADE CONSTRAINTS;
DROP TABLE languages CASCADE CONSTRAINTS;

-- I was thinking of using a sequence to generate a primary key for this table.  However, Oracle 12c introduced
-- identity columns which simplifies sequence generation statements on columns
CREATE TABLE languages(
  language_id INTEGER GENERATED BY DEFAULT AS IDENTITY (
    START WITH 1 INCREMENT BY 1
  ),
  name VARCHAR2(63),
  created DATE
) TABLESPACE ANDY;

ALTER TABLE languages ADD CONSTRAINT languages_id_pk PRIMARY KEY (language_id);

-- All language name values must be unique in the table
-- Specifying a unique constraint also creates an index on the column
ALTER TABLE languages ADD CONSTRAINT languages_name_uq UNIQUE (name);

CREATE TABLE books(
  isbn INTEGER CONSTRAINT books_pk PRIMARY KEY,
  title VARCHAR2(127),
  released DATE
) TABLESPACE ANDY;

-- Since I don't give a name to this constraint, Oracle automatically generates one for me
ALTER TABLE books MODIFY title NOT NULL;

-- Add columns to the existing table
ALTER TABLE books ADD started DATE;
ALTER TABLE books ADD finished DATE;
ALTER TABLE books ADD edition INTEGER;

-- Add a virtual column that determines the number of days spent reading the book
ALTER TABLE books ADD (time_reading AS (finished - started));

-- Add some check constraints to the book table.  This will validate incoming data
ALTER TABLE books ADD CONSTRAINT books_isbn_ck CHECK (isbn > 0);
ALTER TABLE books ADD CONSTRAINT books_dates_ck CHECK (finished >= started);

-- You can't use SYSDATE in check constraints.  The problem with SYSDATE is it's not deterministic (doesn't always
-- return the same result for a specific input).  You could check for input dates with a trigger.

-- Add indexes on commonly queried columns.  Best practice is to create an index when you have queries on a column that
-- retrieve less than 10 percent of the total rows in the table
CREATE INDEX i_books_title ON books(title);

-- List the columns from the tables owned by this user (C##ANDYUSR)
SELECT * FROM SYS.USER_TAB_COLS;

-- Books and languages have a many to many relationship
-- This table represents the relationship by holding foreign keys to each table
CREATE TABLE book_languages(
  isbn INTEGER NOT NULL,
  name VARCHAR2(63),
  CONSTRAINT books_languages_isbn_fk
    FOREIGN KEY (isbn) REFERENCES books(isbn) ON DELETE CASCADE,
  CONSTRAINT book_languages_name_fk
    FOREIGN KEY (name) REFERENCES languages(name) ON DELETE CASCADE
) TABLESPACE ANDY;